

                       term  ::=  "zero"

                               |  "successor"<NO_WHITESPACE>"(" argument ")"

                               |  "predecessor"<NO_WHITESPACE>"(" argument ")"

                               ;

